<#
.SYNOPSIS
Installs the local root CA certificate into a Windows trusted root store.

.DESCRIPTION
Loads the CA certificate generated by create-ca.ps1 from the repository-local
pki folder and imports it into the Windows Trusted Root Certification
Authorities store for either the current user or the local machine.

.PARAMETER CertPath
Path to the CA certificate file to import. Defaults to the repository-local
pki\ca\myCA.pem file.

.PARAMETER StoreLocation
Target certificate store location. Use CurrentUser for per-user trust or
LocalMachine for system-wide trust.

.EXAMPLE
powershell -ExecutionPolicy Bypass -File .\install-ca-cert.ps1

.EXAMPLE
powershell -ExecutionPolicy Bypass -File .\install-ca-cert.ps1 -StoreLocation LocalMachine

.NOTES
Importing into LocalMachine\Root typically requires an elevated PowerShell
session. Use -WhatIf to preview the action.
#>
[CmdletBinding(SupportsShouldProcess = $true, ConfirmImpact = 'Medium')]
param(
    [string]$CertPath,
    [ValidateSet("CurrentUser", "LocalMachine")]
    [string]$StoreLocation = "CurrentUser"
)

$ErrorActionPreference = "Stop"

$scriptRoot = if (-not [string]::IsNullOrWhiteSpace($PSScriptRoot)) {
    $PSScriptRoot
} else {
    Split-Path -Parent $MyInvocation.MyCommand.Path
}

if ([string]::IsNullOrWhiteSpace($CertPath)) {
    $CertPath = Join-Path $scriptRoot "pki\ca\myCA.pem"
}

if (-not (Test-Path $CertPath)) {
    throw "CA certificate not found: $CertPath"
}

if ($StoreLocation -eq "LocalMachine") {
    $currentIdentity = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($currentIdentity)
    $isAdministrator = $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)

    if (-not $isAdministrator) {
        throw "LocalMachine store import requires an elevated PowerShell session."
    }
}

$resolvedCertPath = (Resolve-Path $CertPath).Path
$storePath = "Cert:\$StoreLocation\Root"

if ($PSCmdlet.ShouldProcess($storePath, "Import certificate $resolvedCertPath")) {
    $importedCert = Import-Certificate -FilePath $resolvedCertPath -CertStoreLocation $storePath

    if (-not $importedCert) {
        throw "Certificate import did not return a result."
    }

    Write-Host "CA certificate imported successfully."
    Write-Host "Store    : $storePath"
    Write-Host "Subject  : $($importedCert.Certificate.Subject)"
    Write-Host "Thumbprint: $($importedCert.Certificate.Thumbprint)"
}